class Colors: 
    ACTION_COLOR = "#f01245"
    ACTION_HOVER_COLOR = "#003253"
    ACTION_HOVER_DURATION = 150

    BACKGROUND_COLOR = "#f2f2f3"
    SECONDARY_BACKGROUND_COLOR = "#ffffff"

    LIGHT_TEXT_COLOR = "#FFFFFF"
    DARK_TEXT_COLOR = "#191919"


class Sizing:
    WINDOW_WIDTH = 1000
    WINDOW_HEIGHT = 600
    
    INPUT_WIDTH = 215
    INPUT_HEIGHT = 50
    
    SUBMIT_BUTTON_WIDTH = 215
    SUBMIT_BUTTON_HEIGHT = 50
    
    RADIUS = 25